# Generated by Django 5.2.1 on 2025-06-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='libelle',
            field=models.CharField(choices=[('Admin', 'admin'), ('Superviseur', 'superviseur'), ('Standard', 'standard')], default='Standard'),
        ),
    ]
