# Generated by Django 5.2.1 on 2025-07-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profil_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_fin',
            field=models.DateTimeField(null=True),
        ),
    ]
